name: SAM deploy local
on:
  push:
    branches:
    - master
  pull_request:



  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn workspaces run test